{% set version = "5.7.0" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/r/robotframework-robocop/robotframework_robocop-{{ version }}.tar.gz
    sha256: fcf395cf35cda9c61e9860bbe48a945f428c7d860995278a9d4c5aa6633b32bd
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: 52618663436bb8cd71642274a2a705b292fc11d42728de8d88011cd1cf841ffa

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - robocop=robocop:run_robocop
  script_env:
    - COVERAGE_THRESHOLD=41

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jinja2 >=3.0,<4.0
    - pathspec >=0.9,<0.13
    - platformdirs >=3.2.0,<4.3.0
    - python >={{ python_min }}
    - python-dateutil >=2.8.2
    - pytz >=2022.7
    - robotframework >=3.2.2,<7.2
    - tomli >=2.0.0

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov
    - python {{ python_min }}
    - pyyaml
    - toml
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
