{% set version = "5.8.0" %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/r/robotframework-robocop/robotframework_robocop-{{ version }}.tar.gz
    sha256: 105b1a051a3e1391479c28b239861b8dee97ccef15e2dcc35c6c0ae4ef7446e1
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: 235a43a19815aef9f3ee07f75e6fae047a8455503fd81682c45fae8004c1533a

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - robocop=robocop:run_robocop
  script_env:
    - COVERAGE_THRESHOLD=41

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jinja2 >=3.0,<4.0
    - pathspec >=0.9,<0.13
    - platformdirs >=3.2.0,<4.4.0
    - python >={{ python_min }}
    - python-dateutil >=2.8.2
    - pytz >=2022.7
    - robotframework >=3.2.2,<7.3
    - tomli >=2.0.0

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov
    - python {{ python_min }}
    - pyyaml
    - toml
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
