{% set version = "1.11.1" %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/robotframework-robocop/robotframework-robocop-{{ version }}.tar.gz
    sha256: eb175575af2b7d2b5a1faa1e4835adee325916e9969f1a7b7d4c938bec4d429b
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: a408d6a25349f8437dd595c19db19be28c5a8a3e3162763df2591ed7d2be31c9

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robocop=robocop:run_robocop

requirements:
  host:
    - pip
    - python >=3.6
    - robotframework >=3.2.2
    - toml >=0.10.2
  run:
    - python >=3.6
    - robotframework >=3.2.2
    - toml >=0.10.2

test:
  source_files:
    - src/tests
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help
    - cd src
    - python -c "__import__('pathlib').Path('pytest.ini').write_text('''[pytest]\\naddopts = -k 'not find_project_root_missing_but_git' ''')"
    - coverage run --source=robocop -m pytest
    - coverage report --fail-under=96
  requires:
    - coverage
    - pip
    - pytest
    - pyyaml
    - toml

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
