# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.5.1"

package:
  name: robotframework-robocop
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-robocop/robotframework_robocop-${{ version }}.tar.gz
  sha256: b1e65877f9e9c7483d8bf9e43b6857918ab7be43c1a9506d625d87b662e0342b

build:
  number: 0
  noarch: python
  script:
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - robocop = robocop.run:main

requirements:
  host:
    - hatchling >=1.26.1
    - pip
    - python ${{ python_min }}.*
  run:
    - jinja2 >=3.1.4
    - pathspec >=0.12
    - platformdirs >=4.3
    - python >=${{ python_min }}
    - python-dateutil >=2.8.2
    - pytz >=2022.7
    - rich >=10.11.0
    - robotframework >=4.0,<7.4
    - tomli ==2.2.1
    - tomli-w >=1.0
    - typer-slim >=0.12.5

tests:
  - python:
      imports: robocop
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      recipe:
        - run_test.py
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}
    script:
      - robocop --version
      - robocop --help
      - python run_test.py

about:
  summary: Static code analysis tool (linter) and code formatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/MarketSquare/robotframework-robocop
  documentation: https://robocop.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
